// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetCore5WebAPI.Data;

namespace NetCore5WebAPI.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NetCore5WebAPI.Data.Clinic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clinics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmailAddress = "kandental@gmail.com",
                            Name = "Kan Dental Clinic"
                        },
                        new
                        {
                            Id = 2,
                            EmailAddress = "totdental@gmail.com",
                            Name = "Tot Dental Clinic"
                        },
                        new
                        {
                            Id = 3,
                            EmailAddress = "3timesdental@gmail.com",
                            Name = "3Times Dental Clinic"
                        });
                });

            modelBuilder.Entity("NetCore5WebAPI.Data.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClinicId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClinicId = 1,
                            FirstName = "Lou II",
                            LastName = "de los Reyes",
                            MiddleName = "Bohol",
                            Rating = 5.0
                        },
                        new
                        {
                            Id = 2,
                            ClinicId = 3,
                            FirstName = "Louie",
                            LastName = "Cruz",
                            MiddleName = "Santos",
                            Rating = 4.2999999999999998
                        },
                        new
                        {
                            Id = 3,
                            ClinicId = 2,
                            FirstName = "Jackou",
                            LastName = "Perez",
                            MiddleName = "Lim",
                            Rating = 3.5
                        });
                });

            modelBuilder.Entity("NetCore5WebAPI.Data.Doctor", b =>
                {
                    b.HasOne("NetCore5WebAPI.Data.Clinic", "Clinic")
                        .WithMany()
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinic");
                });
#pragma warning restore 612, 618
        }
    }
}
